// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Entities;
using System;

namespace ReactCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181202191818_changed test ID to id")]
    partial class changedtestIDtoid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Test", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("testString");

                    b.HasKey("id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Entities.Models.Test2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("testString");

                    b.HasKey("ID");

                    b.ToTable("Test2s");
                });
#pragma warning restore 612, 618
        }
    }
}
