export const friendConstants = {
  ADD_TEST: "ADD_TEST",
  ADD_TEST_SUCCESS: "ADD_TEST_SUCCESS",
  ADD_TEST_FAILURE: "ADD_TEST_FAILURE",
  LOAD_TEST_API: "LOAD_TEST_API",
  LOAD_TEST_API_SUCCESS: "LOAD_TEST_API_SUCCESS",
  LOAD_TEST_API_FAILURE: "LOAD_TEST_API_FAILURE",
  CHANGE_ACTIVE_TEST: "CHANGE_ACTIVE_TEST"
};
