export const friendConstants = {
  ADD_FRIEND_ATTEMPT: "ADD_FRIEND_ATTEMPT",
  ADD_FRIEND_SUCCESS: "ADD_FRIEND_SUCCESS",
  ADD_FRIEND_FAILURE: "ADD_FRIEND_FAILURE",
  LOAD_FRIEND_ATTEMPT: "LOAD_FRIEND_ATTEMPT",
  LOAD_FRIEND_SUCCESS: "LOAD_FRIEND_SUCCESS",
  LOAD_FRIEND_FAILURE: "LOAD_FRIEND_FAILURE",
  CHANGE_ACTIVE_FRIEND: "CHANGE_ACTIVE_FRIEND"
};
